### ISSUE TITLE
 按照reademe中的步骤跑到python inference.py报下述错误，这个有什么解决方法吗

### ISSUE THREAD

**Issue by liwenyu0625** [HaxyMoly/Pangu-Weather-ReadyToGo#11]
2023-08-23 16:04:02.8995314 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Pad node. Name:'/b1/Pad_3' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:368 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 411402240   

Traceback (most recent call last):
  File "D:\pycharm\pythonProiect\Pangu-Weather-ReadyToGo\inference.py", line 121, in <module>
    output, output_surface = ort_session.run(None, {'input':input, 'input_surface':input_surface})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Pad node. Name:'/b1/Pad_3' 
Status Message: D:\a\_work\1\s\onnxruntime\core\framework\bfc_arena.cc:368 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 411402240

**Comment by smarttommyau** [comment]
你是内存不足，试试清空后台才运行。
还不行的话把inference.py的97行的30调少
```
options.intra_op_num_threads = 30
```
