### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 20220815gu** [HaxyMoly/Pangu-Weather-ReadyToGo#14]
大家是否尝试过在局部地区进行预测而不是全球范围，我对data_prepare.py进行相关修改，可以下载area = [40, 100, 20, 120]的初始状态数据，但在运行inference.py进行预测时报错：
Traceback (most recent call last):
  File "E:\Pangu-Weather-ReadyToGo-main\inference.py", line 122, in <module>
    output, output_surface = ort_session.run(None, {'input':input, 'input_surface':input_surface})
  File "C:\Users\gujiahui\anaconda3\envs\pgwdome\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input for the following indices
 index: 2 Got: 81 Expected: 721
 index: 3 Got: 81 Expected: 1440
 Please fix either the inputs or the model.
该如何修改以能够在可选区域内进行预测呢？

**Comment by smarttommyau** [comment]
不行，模型要求全球的数据才能运行
