### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by bravelyi** [HaxyMoly/Pangu-Weather-ReadyToGo#17]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\code\qx\Pangu-Weather-ReadyToGo-main\inference.py", line 104, in &lt;module&gt;
    ort_session = ort.InferenceSession(model_used, sess_options=options, providers=[('CUDAExecutionProvider', cuda_provider_options)])
  File "D:\Anaconda3\envs\pangu\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\Anaconda3\envs\pangu\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 408, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s
\onnxruntime\core\providers\cuda\cuda_call.cc:124 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUDNN failure 1: CUDNN_STATUS_NOT_INITIALIZED ; GPU=0 ; hostname=WIN-PS05E4J14Q1 ; expr=cudnnCreate(&amp;cudnn_handle_);

**Comment by bravelyi** [comment]
你们有人在运行inference.py时遇到这个问题吗

**Comment by smarttommyau** [comment]
你是用了gpu版的吗？可能你安装onnxruntime 有问题
